In [2]:
import pandas as pd

In [3]:
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('C:\Codebasics\exercise.csv')


In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
import math

In [9]:
from word2number import w2n

In [7]:
import word2number

ModuleNotFoundError: No module named 'word2number'

In [10]:
from word2number import w2n

In [11]:
print(w2n.word_to_num(df.experience.values)

SyntaxError: unexpected EOF while parsing (<ipython-input-11-facfc65fb530>, line 1)

In [12]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [13]:
df=df.rename(columns = {'test_score(out of 10)':'test_s'})

In [14]:
df=df.rename(columns = {'interview_score(out of 10)':'interview_s'})

In [15]:
df=df.rename(columns = {'salary($)':'salary'})

In [16]:
df

experience  test_s  interview_s  salary
0        NaN     8.0            9   50000
1        NaN     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     NaN            7   72000
7     eleven     7.0            8   80000

In [17]:
median_test = math.floor(df.test_s.median())

print(median_test)

In [18]:
print(median_test)

8


In [19]:
df.test_s = df.test_s.fillna(median_test)

In [20]:
df

experience  test_s  interview_s  salary
0        NaN     8.0            9   50000
1        NaN     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     8.0            7   72000
7     eleven     7.0            8   80000

In [33]:
df

experience  test_s  interview_s  salary
0        NaN     8.0            9   50000
1        NaN     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     8.0            7   72000
7     eleven     7.0            8   80000

In [21]:
df.experience = df.experience.fillna(0)

In [22]:
df

experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     8.0            7   72000
7     eleven     7.0            8   80000

In [44]:
df

experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     8.0            7   72000
7     eleven     7.0            8   80000

In [23]:
for index, row in df.iterrows():
   print (index)

0
1
2
3
4
5
6
7


In [29]:
df['experience'] 

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [31]:
df.experience

0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [32]:
df.experience = w2n.word_to_num(df.experience)

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

df

In [33]:
df

experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2       five     6.0            7   60000
3        two    10.0           10   65000
4      seven     9.0            6   70000
5      three     7.0           10   62000
6        ten     8.0            7   72000
7     eleven     7.0            8   80000

In [81]:
for index, row in df.iterrows():
    row[index] = w2n.word_to_num(row['experience'])

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [36]:
w2n.word_to_num(df.experience[1])

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [35]:
for index, row in df.iterrows():
    df.experience[index] = w2n.word_to_num(df.experience[index])

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [39]:
for x in range(2, 8):
    df.experience[x] = w2n.word_to_num(df.experience[x])

C:\Users\sharma3n\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [40]:
df

experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2          5     6.0            7   60000
3          2    10.0           10   65000
4          7     9.0            6   70000
5          3     7.0           10   62000
6         10     8.0            7   72000
7         11     7.0            8   80000

In [41]:
reg = linear_model.LinearRegression()

In [48]:
reg.fit(df[['experience','test_s','interview_s']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
reg.coef_

array([ 2922.26901502,  2221.30909959,  2147.48256637])

In [50]:
reg.intercept_

14992.65144669314

In [51]:
reg.predict([[2, 9, 6]])

array([ 53713.86677124])

In [53]:
reg.predict([[12, 10, 10]])

array([ 93747.79628651])

In [47]:
df.test_s[6] = 7
df

C:\Users\sharma3n\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2          5     6.0            7   60000
3          2    10.0           10   65000
4          7     9.0            6   70000
5          3     7.0           10   62000
6         10     7.0            7   72000
7         11     7.0            8   80000

In [54]:
df.salary

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [61]:
df.salary.iloc[x:x+2]

2    60000
3    65000
Name: salary, dtype: int64

In [58]:
x=2

In [60]:
x

2

In [64]:
df[['experience','test_s','interview_s']].iloc[x:x+4]

experience  test_s  interview_s
2          5     6.0            7
3          2    10.0           10
4          7     9.0            6
5          3     7.0           10

In [70]:
reg.fit(df[['experience','test_s','interview_s']].iloc[x:x+5],df.salary.iloc[x:x+5])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [71]:
reg.coef_, reg.intercept_

(array([ 1952.62557078,  2027.58751903,   929.79452055]), 32002.283105022856)

In [72]:
reg.get_params

<bound method BaseEstimator.get_params of LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)>

In [73]:
df

experience  test_s  interview_s  salary
0          0     8.0            9   50000
1          0     8.0            6   45000
2          5     6.0            7   60000
3          2    10.0           10   65000
4          7     9.0            6   70000
5          3     7.0           10   62000
6         10     7.0            7   72000
7         11     7.0            8   80000